import Vuex from "vuex";
import Vue from "vue";

//load Vuex
Vue.use(Vuex);

//to handle state
const state = {
  selectedCalcItem:  {
    id: "",
    acronym: "",
    icon: "",
    title: " ",
    description: "",
    value1: { icon: "", desc: "" },
    value2: { icon: "", desc: "" },
    calcDescription:
      "",
  },
  listItems: [
    {
      id: "2",
      acronym: "CR",
      icon: "conversion",
      title: "Conversion Rate",
      description: "Leads / Conversions",
      value1: { icon: "cvr-1", desc: "Conversion" },
      value2: { icon: "cvr-2", desc: "Clicks" },
      calcDescription:
        "The number of conversions divided by the total number of visitors.",
    },
    {
      id: "3",
      acronym: "ROMI",
      icon: "save-money",
      title: "Return on Marketing Investment",
      description: "Expressed as percentage",
      value1: { icon: "rmi-1", desc: "Sales Growth" },
      value2: { icon: "rmi-2", desc: "Marketing Cost" },
      calcDescription: "Calculate the return gained from marketing campaign.",
    },
    {
      id: "1",
      acronym: "CTR",
      icon: "click-through-rate",
      title: "Click-Through Rate",
      description: "CTR",
      value1: { icon: "cvr-2", desc: "Clicks" },
      value2: { icon: "ctr-2", desc: "Impressions" },
      calcDescription:
        "The percentage of people that click a link of the number that saw it.",
    },
    {
      id: "4",
      acronym: "Lead CR",
      icon: "conversion-rate",
      title: "Website to Lead Conversion Rate",
      description: "Lead CR",
      value1: { icon: "wld", desc: "Number of Leads" },
      value2: { icon: "wld-2", desc: "Website Visitors" },
      calcDescription:
        "The percentage of website visitors that are converted into leads.",
    },
    {
      id: "5",
      acronym: "Customer CR",
      icon: "switch (1)",
      title: "Lead to Customer Conversion Rate",
      description: "Customer CR",
      value1: { icon: "users", desc: "Number of Customers" },
      value2: { icon: "hand-user", desc: "Number of Leads" },
      calcDescription: "The percentage of leads that become a customer.",
    },
    {
      id: "6",
      acronym: "Landing Page CR",
      icon: "seo-landing-pages-symbol-inside-a-circle",
      title: "Landing Page Conversion Rate",
      description: "Landing Page CR",
      value1: { icon: "hand-user", desc: "Number of Leads" },
      value2: { icon: "visitor (1)", desc: "Number of Page Visitors" },
      calcDescription:
        "The percentage of visitors to a page that became a lead.",
    },
    {
      id: "7",
      acronym: "CPLA",
      icon: "cpl",
      title: "Cost per Lead Acquisition",
      description: "CPL",
      value1: { icon: "hand-cost", desc: "Cost of Campaign" },
      value2: { icon: "hand-user", desc: "Number of Leads" },
      calcDescription: "The cost to acquire one lead.",
    },
    {
      id: "8",
      acronym: "CAC",
      icon: "Group 96",
      title: "Customer Acquisition Cost",
      description: "CAC",
      value1: { icon: "hand-cost", desc: "Cost of Campaign" },
      value2: { icon: "users", desc: "Number of Customers" },
      calcDescription: "The cost to acquire one lead.",
    },
    {
      id: "9",
      acronym: "CLV",
      icon: "value",
      title: "Customer Lifetime Value",
      description: "CLV",
      value1: { icon: "order", desc: "Average Order Value" },
      value2: { icon: "sales (1)", desc: "No. of Repeat Sales in Lifetime" },
      calcDescription:
        "The revenue an average customer will provide a company in their lifetime.",
    },
    {
      id: "10",
      acronym: "CR Needed",
      icon: "increase",
      title: "Company Revenue from Marketing p/Year",
      description: "CR Needed",
      value1: { icon: "users", desc: "Avg. Customer Spend p/year" },
      value2: { icon: "target", desc: "Customer Goal in one year" },
      calcDescription:
        "The amount of revenue generated by acquiring new customers.",
    },
    {
      id: "11",
      acronym: "Budget p/year",
      icon: "bullhorn",
      title: "Marketing Campaign Budget Needed p/Year",
      description: "",
      value1: { icon: "hand-cost", desc: "Revenue Needed P/Year" },
      value2: { icon: "none", desc: "none" },
      calcDescription:
        "Forecast the marketing budget required to achieve the desired revenue.",
    },
    {
      id: "12",
      acronym: "Budget p/year",
      icon: "Path 351",
      title: "Overall Campaign Budget Needed (Based on Lifetime Spend)",
      description: "",
      value1: { icon: "manmark", desc: "Value of Average Customer Lifetime" },
      value2: { icon: "none", desc: "none" },
      calcDescription:
        "Forecast the overall campaign budget needed based on customer lifetime value.",
    },
    {
      id: "13",
      acronym: "CRR",
      icon: "retention",
      title: "Customer Retention Rate",
      description: "",
      value1: { icon: "finish-line", desc: "Customers at END of period" },
      value2: { icon: "rocket", desc: "Customers at START of period" },
      calcDescription:
        "Calculate how many customers have stopped using your business.",
    },
  ],
};

//to handle state
const getters = {
  getSelectedItem() {
    return state.selectedCalcItem;
  },
};

//to handle actions
const actions = {
  setSelectedItem({ commit },  data ) {
    console.log('data in setSelectedItem',data)
    commit("SET_SELECTED_ITEM", 
      data,
    );
  },
};

//to handle mutations
const mutations = {
  SET_SELECTED_ITEM(state, data) {
    console.log('DATA IN MU',data)
    state.selectedCalcItem.id = data.id;
    state.selectedCalcItem.acronym = data.acronym;
    state.selectedCalcItem.icon = data.icon;
    state.selectedCalcItem.title = data.title;
    state.selectedCalcItem.description = data.description;
    state.selectedCalcItem.value1 = data.value1;
    state.selectedCalcItem.value2 = data.value2;
    state.selectedCalcItem.calcDescription = data.calcDescription;
  },
};

//export store module
export default new Vuex.Store({
  state,
  getters,
  actions,
  mutations,
});
